export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum StudentType {
  FRESHER = 'FRESHER',
  EXPERIENCED = 'EXPERIENCED',
}

export enum TrainingStatus {
  ENROLLED = 'ENROLLED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  DROPPED = 'DROPPED',
  ON_HOLD = 'ON_HOLD',
}

export enum PlacementStatus {
  NOT_LOOKING = 'NOT_LOOKING',
  LOOKING_FOR_JOB = 'LOOKING_FOR_JOB',
  INTERVIEWING = 'INTERVIEWING',
  PLACED = 'PLACED',
  NOT_PLACED = 'NOT_PLACED',
}

export enum CourseMode {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  HYBRID = 'HYBRID',
}

export enum CourseStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum BatchStatus {
  UPCOMING = 'UPCOMING',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum EnquiryStatus {
  NEW = 'NEW',
  CONTACTED = 'CONTACTED',
  FOLLOW_UP = 'FOLLOW_UP',
  INTERESTED = 'INTERESTED',
  NOT_INTERESTED = 'NOT_INTERESTED',
  CONVERTED = 'CONVERTED',
  LOST = 'LOST',
}

export enum EnquirySource {
  WEBSITE = 'WEBSITE',
  WALK_IN = 'WALK_IN',
  PHONE = 'PHONE',
  REFERRAL = 'REFERRAL',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  OTHER = 'OTHER',
}

export enum FollowUpStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  RESCHEDULED = 'RESCHEDULED',
  CANCELLED = 'CANCELLED',
}

export enum JobApplicationStatus {
  APPLIED = 'APPLIED',
  SHORTLISTED = 'SHORTLISTED',
  INTERVIEW = 'INTERVIEW',
  SELECTED = 'SELECTED',
  REJECTED = 'REJECTED',
  OFFER_RECEIVED = 'OFFER_RECEIVED',
  JOINED = 'JOINED',
}

export enum InterviewStatus {
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  RESCHEDULED = 'RESCHEDULED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
}

export enum InterviewResult {
  PENDING = 'PENDING',
  SELECTED = 'SELECTED',
  REJECTED = 'REJECTED',
}

export enum NotificationType {
  NEW_ENQUIRY = 'NEW_ENQUIRY',
  FOLLOW_UP_DUE = 'FOLLOW_UP_DUE',
  STUDENT_ADDED = 'STUDENT_ADDED',
  RESUME_UPLOADED = 'RESUME_UPLOADED',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
  STUDENT_PLACED = 'STUDENT_PLACED',
  USER_CREATED = 'USER_CREATED',
  ENQUIRY_ASSIGNED = 'ENQUIRY_ASSIGNED',
}

export enum AuditAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_ACTIVATED = 'USER_ACTIVATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  USER_DELETED = 'USER_DELETED',
  PERMISSION_CHANGED = 'PERMISSION_CHANGED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  STUDENT_CREATED = 'STUDENT_CREATED',
  STUDENT_UPDATED = 'STUDENT_UPDATED',
  STUDENT_DELETED = 'STUDENT_DELETED',
  RESUME_UPLOADED = 'RESUME_UPLOADED',
  RESUME_DELETED = 'RESUME_DELETED',
  ENQUIRY_CREATED = 'ENQUIRY_CREATED',
  ENQUIRY_UPDATED = 'ENQUIRY_UPDATED',
  ENQUIRY_ASSIGNED = 'ENQUIRY_ASSIGNED',
  ENQUIRY_DELETED = 'ENQUIRY_DELETED',
  PLACEMENT_UPDATED = 'PLACEMENT_UPDATED',
  COURSE_CREATED = 'COURSE_CREATED',
  COURSE_UPDATED = 'COURSE_UPDATED',
  COURSE_DELETED = 'COURSE_DELETED',
  BATCH_CREATED = 'BATCH_CREATED',
  BATCH_UPDATED = 'BATCH_UPDATED',
  BATCH_DELETED = 'BATCH_DELETED',
}
