import { PERMISSIONS, PermissionKey } from './permissions.constant';

export enum RoleName {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  COUNSELOR = 'COUNSELOR',
  TRAINER = 'TRAINER',
  PLACEMENT_OFFICER = 'PLACEMENT_OFFICER',
  STAFF = 'STAFF',
}

export const DEFAULT_ROLE_PERMISSIONS: Record<RoleName, PermissionKey[]> = {
  [RoleName.OWNER]: Object.values(PERMISSIONS) as PermissionKey[],
  [RoleName.ADMIN]: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.STUDENTS_CREATE,
    PERMISSIONS.STUDENTS_EDIT,
    PERMISSIONS.COURSES_VIEW,
    PERMISSIONS.COURSES_CREATE,
    PERMISSIONS.COURSES_EDIT,
    PERMISSIONS.BATCHES_VIEW,
    PERMISSIONS.BATCHES_CREATE,
    PERMISSIONS.BATCHES_EDIT,
    PERMISSIONS.PLACEMENTS_VIEW,
    PERMISSIONS.PLACEMENTS_EDIT,
    PERMISSIONS.RESUMES_VIEW,
    PERMISSIONS.RESUMES_UPLOAD,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.MOCK_VIEW,
    PERMISSIONS.MOCK_EDIT,
  ],
  [RoleName.COUNSELOR]: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.STUDENTS_CREATE,
    PERMISSIONS.STUDENTS_EDIT,
    PERMISSIONS.ENQUIRIES_VIEW,
    PERMISSIONS.ENQUIRIES_EDIT,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.MOCK_VIEW,
  ],
  [RoleName.TRAINER]: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.COURSES_VIEW,
    PERMISSIONS.BATCHES_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.MOCK_VIEW,
    PERMISSIONS.MOCK_CREATE,
    PERMISSIONS.MOCK_EDIT,
  ],
  [RoleName.PLACEMENT_OFFICER]: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.PLACEMENTS_VIEW,
    PERMISSIONS.PLACEMENTS_CREATE,
    PERMISSIONS.PLACEMENTS_EDIT,
    PERMISSIONS.RESUMES_VIEW,
    PERMISSIONS.RESUMES_UPLOAD,
    PERMISSIONS.RESUMES_DELETE,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.MOCK_VIEW,
  ],
  [RoleName.STAFF]: [PERMISSIONS.NOTIFICATIONS_VIEW],
};

export const PROTECTED_ROLES = [RoleName.OWNER];
